### ISSUE TITLE
Feedback - Sabrina

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/DSCI-532_Linyang-Alex#24]
Good:
- very intuitive in most parts
- colouring is very enjoyable
- The team understands the data well as they only present countries with large data points.
- The map to the positive and negative attitudes is very straightforward and easy to comprehend.

Improvement:
- Description for working flexibility , how did you rank them?
- Gender section: instead of using "all conditions included", it is better to use " all".
- Family History: instead of using " all conditions included", think of a better way to say no filter applied etc.
- Treatment For Mental Health - same thing as the previous point. (edited)

**Comment by lyyu0413** [comment]
Thank you for the advices!

- Add description of working flexibility;
- rephrase the 'all'
