### ISSUE TITLE
Feedback - Alex 

### ISSUE THREAD

**Issue by pak-alex** [UBC-MDS/DSCI-532_Linyang-Alex#25]
* Overall the app is really good, the filters make sense and the app is clean to look at 
* Map is pretty and labels are nice 
* "Working Flexibility" variable should be described more, I don't know what it means without someone explaining to me 
* Maybe clarify that Working Flexibility is a threshold filter, I thought it re-normalized the data every time you changed the ranges
* Maybe change the colour scheme for the bar charts

**Comment by lyyu0413** [comment]
Thank you so much for the advices!

- Add description of working flexibility;
- changed colour scheme
