### ISSUE TITLE
Milestone 2 TA feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI-532_Linyang-Alex#26]
* Repo well organized. Easy to find all files. I think you are just missing the code of conduct.
* Thanks for adding the functionality demo :)

The app:
* An error appears when making a selection that doesn’t have any data. Make sure to fix these issues.
* Define the working flexibility factor.
* I believe making the map interactive will encourage engagement from users. Great that you are considering this for next steps.
* Maybe just say “all genders” instead of all condition included which sounds a bit weird for gender.
* Consider making the percentages in the bar chart larger/attractive.

Code:
* Provide more key comments.
* Adding lines between code lines is a bit distracting, avoid this as they are unnecessary.
* Try to make the code lines shorter, adding tabs instead.

**Comment by lyyu0413** [comment]
Thank you for the advice!

Now:
- Added the code of conduct;

- Still trying to fix the error, tried if else for NA selection. Still got an error. Might have to fix the issue next milestone;

- implanted the leaflet, now the map plot is interactive!
- Add definition of working flexibility in the app
- re-phrased the 'all' selection 

Next step:

- make interactive bar chart
